config/routes.rb
Rails.application.routes.draw do
  # resources :topics
  # resources :posts
  # changed resources to show passing resources :posts block to resources :topics block for nesting
    resources :topics do
      resources :posts, except: [:index]
    end

   # use only: [ ] so no /posts/:id routes are created,
   #  just posts/:post_id/comments routes
   #  add create and destroy routes for comments
   #  comments will display on posts show view, so index, new arent needed
   #  also users won't view or edit indiv comments, so show, update & edit aren't needed

   resources :posts, only: [] do
     resources :comments, only: [:create, :destroy]
     resources :favorites, only: [:create, :destroy]

     post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
   end

   #create new and create actions, only hash key prevents unnec. route code
    resources :users, only:[:new, :create, :show]

    resources :sessions, only: [:new, :create, :destroy]
#  get 'welcome/index'

#  get 'welcome/about'

# remove the get "welcome/index" because the root is declared as index
# modify the about route to allow users to visit/about rather than /welcome/about

  get 'about' => 'welcome#about'

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # 2 register an inline callback directly after before_save callback
  # self_email = email.downase is the code that will run when the callback executes
  # callback are hooks that trigger logic before/after an alteration of an object’s state
   has_many :posts, dependent: :destroy
   has_many :comments, dependent: :destroy
   has_many :votes, dependent: :destroy
   has_many :favorites, dependent: :destroy

   before_save { self.role ||= :member }
   # the code in {...||...} is shorthand for
   # self.role = :member if self.role.nil?

  # 3 use Ruby’s validates function to ensure name is present & min/max length
   validates :name, length: { minimum: 1, maximum: 100 }, presence: true

 # 4 validate with that password is valid,
  # ensure that updated password is 6 char long,
  # allow_blank: true skips validation if no password is given
  # allowing changing other attributes on user without updating password
  validates :password, presence: true, length: { minimum: 6 }, if: "password_digest.nil?"
  validates :password, length: { minimum: 6 }, allow_blank: true

 # 5 validate email present, unique, case insensitive, min/max length, formatted for email
   validates :email,
             presence: true,
             uniqueness: { case_sensitive: false },
             length: { minimum: 3, maximum: 254 }

  # 6 use Ruby’s has_secure_password, has_secure_password
   #  to add methods to set and authenticate against a BCrypt password
   # requires a password_digest attribute
   has_secure_password

   enum role: [:member, :admin]

   def favorite_for(post)
     favorites.where(post_id: post.id).first
   end

   def avatar_url(size)
     gravatar_id = Digest::MD5::hexdigest(self.email).downcase
     "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
   end

   def has_posts?
     posts.count > 0
   end

   def has_comments?
     comments.count > 0
   end

   def has_favorites?
     favorites.count > 0
   end
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
  # create a user with new and set attributes from params hash
     @user = User.new
     @user.name = params[:user][:name]
     @user.email = params[:user][:email]
     @user.password = params[:user][:password]
     @user.password_confirmation = params[:user][:password_confirmation]

     # save the new user,
     # if successful, message user and redirect to root path
     # if not, display error and render new view to try again
     if @user.save
       flash[:notice] = "Welcome to Bloccit #{@user.name}!"
       create_session(@user)
       redirect_to root_path
     else
       flash.now[:alert] = "There was an error creating your account. Please try again."
       render :new
     end
   end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.visible_to(current_user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_favorite.html.erb
<div class="media">
  <%= render partial: 'votes/voter', locals: { post: post } %>
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to post.title, topic_post_path(post.topic, post) %>
    </h4>
    <small>
      <%= image_tag post.user.avatar_url(48), class: "gravatar", style: "float: left; margin-top: 5px" %>
      <%= time_ago_in_words(post.created_at) %> ago.
      <br>
      Submitted by <%= post.user.name %> <br>
      <%= post.comments.count %> Comments
    </small>
  </div>
</div>

app/views/users/confirm.html.erb
<h2>Sign Up Confirmation</h2>

<div class="row">

  <div class="col-md-4">
    <h4>Are you sure this information is correct?</h4>
    <h5>Email: <%= @user.email%></h5>
    <h5>Name: <%= @user.name%></h5>
  </div>
</div>


<div class="row">
  <div class="col-md-4", style="width: auto;">
    <%= button_to "Yes", {:controller => "users", :action => "create", :params => params}, class: 'btn btn-success'  %>
  </div>
  <div class="col-md-4", style="width: auto;">
    <%= button_to "No", {:controller => "users", :action => "new"}, class: 'btn btn-failure', :method => :get  %>
  </div>
</div>

app/views/users/new.html.erb
 <h2>Sign up</h2>

 <div class="row">
   <div class="col-md-8">
     <%= form_for @user, :url => { :action => :confirm } do |f| %>
 <!—check errors hash on @user provided by ActiveModel:Errors
       and display error messages-->
       <% if @user.errors.any? %>
         <div class="alert alert-danger">
           <h4>There are <%= pluralize(@user.errors.count, "error") %>.</h4>
           <ul>
             <% @user.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
             <% end %>
           </ul>
         </div>
       <% end %>
       <!—add form fields for name and email
       and virtual attributes provided by
       has_secure_password: password and password_confirmation -->
       <%= form_group_tag(@user.errors[:name]) do %>
         <%= f.label :name %>
         <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter name" %>
       <% end %>
       <%= form_group_tag(@user.errors[:email]) do %>
         <%= f.label :email %>
         <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
       <% end %>
       <%= form_group_tag(@user.errors[:password]) do %>
         <%= f.label :password %>
         <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
       <% end %>
       <%= form_group_tag(@user.errors[:password_confirmation]) do %>
         <%= f.label :password_confirmation %>
         <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
       <% end %>
       <div class="form-group">
         <%= f.submit "Sign up", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/users/show.html.erb
<div class="row">
   <div class="col-md-8">
     <div class="media">
       <br />
       <!-- call avatar_url to fetch the current users's avatar -->
       <% avatar_url = @user.avatar_url(128) %>
       <% if avatar_url %>
         <div class="media-left">
           <!--  // use Rails' image_tag method to create an img  -->
           <%= image_tag avatar_url, class: 'media-object' %>
         </div>
       <% end %>
       <div class="media-body">
         <h2 class="media-heading"><%= @user.name %></h2>
         <small>
           <%= pluralize(@user.posts.count, 'post') %>,
           <%= pluralize(@user.comments.count, 'comment') %>
         </small>
       </div>
     </div>
   </div>
 </div>

 <! -- display all of the use's posts and comments using partials -->
 <h2>Posts</h2>
<% if @user.has_posts? %>
  <%= render @user.posts %>
<% else %>
  <div class="media">
    <%= link_to current_user.name, user_path(current_user) %> has not submitted any posts yet.
  </div>
<% end %>

 <h2>Comments</h2>
<% if @user.has_comments? %>
  <%= render @user.comments %>
<% else %>
  <div class="media">
    <%= link_to current_user.name, user_path(current_user) %> has not submitted any comments yet.
  </div>
<% end %>

<h2>Favorites</h2>
<% if @user.has_favorites? %>
    <% @user.favorites.each do |favorite| %>
      <%= render partial: 'users/favorite', locals: { post: favorite.post } %>
    <% end %>
<% else %>
    <div class="media">
      <%= link_to current_user.name, user_path(current_user) %> has not favorited any posts yet.
    </div>
<% end %>