config/routes.rb
Rails.application.routes.draw do
  # resources :topics
  # resources :posts
  # changed resources to show passing resources :posts block to resources :topics block for nesting
    resources :topics do
      resources :posts, except: [:index]
    end

   # use only: [ ] so no /posts/:id routes are created,
   #  just posts/:post_id/comments routes
   #  add create and destroy routes for comments
   #  comments will display on posts show view, so index, new arent needed
   #  also users won't view or edit indiv comments, so show, update & edit aren't needed

   resources :posts, only: [] do
     resources :comments, only: [:create, :destroy]
     resources :favorites, only: [:create, :destroy]

     post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
   end

   #create new and create actions, only hash key prevents unnec. route code
    resources :users, only:[:new, :create, :show]

    resources :sessions, only: [:new, :create, :destroy]
#  get 'welcome/index'

#  get 'welcome/about'

# remove the get "welcome/index" because the root is declared as index
# modify the about route to allow users to visit/about rather than /welcome/about

  get 'about' => 'welcome#about'

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def faq
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

<button class='social-btn'><%= link_to "Follow me", "https://twitter.com/barbperlik", class: "social-btn" %>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<h3>[Email Contact]<mailto:barbperlik@gmail.com>

app/views/welcome/faq.html.erb
<h1>Welcome#faq</h1>
<p>This is a faq page to help you use bloccit.</p>

app/views/welcome/index.html.erb
 <br>
 <div class="jumbotron">
   <h1>Bloccit</h1>
   <p>Bloccit is a resource for sharing links with your friends!</p>
   <p>
   <%= link_to "Sign In", new_session_path %> or
   <%= link_to "Sign Up", new_user_path, class: 'btn btn-primary' %> today!
   </p>
 </div>

 <div class="row">
   <div class="col-md-4">
     <h2>Solves world hunger</h2>
     <p>Bloccit will deliver food and water to those in need, all over the world.</p>
   </div>
   <div class="col-md-4">
     <h2>Eliminates poverty</h2>
     <p>Bloccit will deliver money and education to those in need, all over the world.</p>
   </div>
   <div class="col-md-4">
     <h2>Makes you better looking</h2>
     <p>Bloccit will make you better looking: it's scientifically proven to make men look like Ryan Gosling and women look like Shakira.</p>
   </div>
 </div>